.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH QTSTALKER 1 "July 4, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
qtstalker \- stock and commodity market charting and technical analysis
.SH SYNOPSIS
.B qtstalker
.SH DESCRIPTION
This manual page was written for the Debian distribution because the
original program does not have a manual page. Instead, it has documentation
in HTML format (see below).
.SH "SEE ALSO"
The HTML documentation installed by package qtstalker-doc:
.B /usr/share/doc/qtstalker-doc/html/index.html
.TP
The Qtstalker project at SourceForge:
.B http://qtstalker.sourceforge.net/
.SH FILES
Qtstalker stores its data in
.B ~/.qtstalker
and keeps its settings in
.B ~/.qt/qtstalkerrc.
It uses no system-wide configuration files.
.SH AUTHOR
This manual page was written by Marco van Zwetselaar <zwets@zwets.com>,
for the Debian project (but may be used by others).
